//! End-to-end tests driving the `giant-gen` binary against a temp workspace
//! with fake generators (shell scripts declared via `command:`).

use std::fs;
use std::os::unix::fs::PermissionsExt;
use std::path::Path;
use std::process::{Command, Output};

fn bin() -> &'static str {
    env!("CARGO_BIN_EXE_giant-gen")
}

fn workspace() -> tempfile::TempDir {
    let d = tempfile::tempdir().unwrap();
    fs::write(d.path().join("giant.yaml"), "workspace:\n  name: test\n").unwrap();
    d
}

fn write_exec(path: &Path, body: &str) {
    fs::write(path, body).unwrap();
    fs::set_permissions(path, fs::Permissions::from_mode(0o755)).unwrap();
}

fn run(dir: &Path, args: &[&str]) -> Output {
    Command::new(bin())
        .args(args)
        .current_dir(dir)
        .output()
        .unwrap()
}

/// A well-behaved generator: writes a deterministic giant.fake.yaml under
/// the output root.
const GOOD: &str = r#"#!/bin/sh
set -e
mkdir -p "$GIANT_GEN_OUT/pkg"
cat > "$GIANT_GEN_OUT/pkg/giant.fake.yaml" <<'YAML'
# generated by fake
targets:
  - name: x
    outputs: ["out"]
    command: "true"
YAML
"#;

fn setup_good() -> tempfile::TempDir {
    let ws = workspace();
    write_exec(&ws.path().join("fake-gen.sh"), GOOD);
    fs::write(
        ws.path().join("giant-gen.yaml"),
        "generators:\n  - name: fake\n    command: ./fake-gen.sh\n",
    )
    .unwrap();
    ws
}

#[test]
fn runs_generator_and_writes_in_place() {
    let ws = setup_good();
    let out = run(ws.path(), &[]);
    assert!(
        out.status.success(),
        "stderr: {}",
        String::from_utf8_lossy(&out.stderr)
    );
    let f = ws.path().join("pkg/giant.fake.yaml");
    assert!(f.exists(), "expected generated file");
    assert!(fs::read_to_string(&f).unwrap().contains("name: x"));
}

#[test]
fn check_clean_passes() {
    let ws = setup_good();
    run(ws.path(), &[]); // commit a correct file
    let out = run(ws.path(), &["--check"]);
    assert!(out.status.success(), "check should pass on a fresh tree");
    assert!(String::from_utf8_lossy(&out.stdout).contains("fake\tok"));
}

#[test]
fn check_detects_content_drift() {
    let ws = setup_good();
    run(ws.path(), &[]);
    // Simulate "edited sources, forgot to regenerate": the committed file no
    // longer matches what the generator produces.
    fs::write(ws.path().join("pkg/giant.fake.yaml"), "stale\n").unwrap();
    let out = run(ws.path(), &["--check"]);
    assert!(!out.status.success(), "drift should fail the check");
    let s = String::from_utf8_lossy(&out.stdout);
    assert!(s.contains("fake\tDRIFT"), "{s}");
    assert!(s.contains("content differs"), "{s}");
}

#[test]
fn check_flags_file_missing_from_tree() {
    let ws = setup_good();
    run(ws.path(), &[]);
    fs::remove_file(ws.path().join("pkg/giant.fake.yaml")).unwrap();
    let out = run(ws.path(), &["--check"]);
    assert!(!out.status.success());
    assert!(String::from_utf8_lossy(&out.stdout).contains("missing from tree"));
}

#[test]
fn ownership_violation_is_rejected() {
    let ws = workspace();
    // A generator that writes a file it does not own.
    write_exec(
        &ws.path().join("bad-gen.sh"),
        "#!/bin/sh\nset -e\ntouch \"$GIANT_GEN_OUT/oops.txt\"\n",
    );
    fs::write(
        ws.path().join("giant-gen.yaml"),
        "generators:\n  - name: fake\n    command: ./bad-gen.sh\n",
    )
    .unwrap();
    let out = run(ws.path(), &["--check"]);
    assert!(!out.status.success());
    assert!(
        String::from_utf8_lossy(&out.stdout).contains("does not own"),
        "stdout: {}",
        String::from_utf8_lossy(&out.stdout)
    );
}

#[test]
fn unknown_generator_name_errors() {
    let ws = setup_good();
    let out = run(ws.path(), &["nope"]);
    assert!(!out.status.success());
    assert!(
        String::from_utf8_lossy(&out.stderr).contains("no generator named 'nope'"),
        "stderr: {}",
        String::from_utf8_lossy(&out.stderr)
    );
}

#[test]
fn no_generators_is_a_noop() {
    let ws = workspace(); // no giant-gen.yaml
    let out = run(ws.path(), &[]);
    assert!(out.status.success());
}

#[test]
fn failing_generator_fails_the_run() {
    let ws = workspace();
    write_exec(
        &ws.path().join("boom.sh"),
        "#!/bin/sh\necho 'kaboom' >&2\nexit 3\n",
    );
    fs::write(
        ws.path().join("giant-gen.yaml"),
        "generators:\n  - name: fake\n    command: ./boom.sh\n",
    )
    .unwrap();
    let out = run(ws.path(), &[]);
    assert!(!out.status.success());
}
